In [27]:
import pandas as pd

In [28]:
data=pd.read_csv("C:\\Users\\DELL\\Downloads\\DATASCIENCE ASSIGNMENTS\\Online retail.csv")

In [30]:
print(data.columns)

Index(['shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil'], dtype='object')

In [47]:
from mlxtend.preprocessing import TransactionEncoder
# Convert the column with item lists into a list of lists
transactions = data['shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil'].apply(lambda x: x.split(','))
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)
df.head()

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# Data Preprocessing:

In [49]:
df.isnull().sum().sum()

0

In [51]:
df.drop_duplicates(inplace=True)
df.shape

(5153, 120)

# Association Rule Mining:

In [53]:
from mlxtend.frequent_patterns import apriori,association_rules

In [56]:
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)
frequent_itemsets

      support                               itemsets
0    0.029303                              (almonds)
1    0.011062                    (antioxydant juice)
2    0.045993                              (avocado)
3    0.012614                                (bacon)
4    0.015525                       (barbecue sauce)
..        ...                                    ...
431  0.014749  (spaghetti, olive oil, mineral water)
432  0.016689   (spaghetti, pancakes, mineral water)
433  0.012420     (shrimp, spaghetti, mineral water)
434  0.010867       (spaghetti, soup, mineral water)
435  0.013584   (spaghetti, mineral water, tomatoes)

[436 rows x 2 columns]

In [58]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(mineral water),(almonds),0.299825,0.029303,0.010867,0.036246,1.236923,0.002082,1.007204,0.273564
1,(almonds),(mineral water),0.029303,0.299825,0.010867,0.370861,1.236923,0.002082,1.112909,0.197325
2,(chocolate),(avocado),0.203765,0.045993,0.010285,0.050476,1.097484,0.000914,1.004722,0.111557
3,(avocado),(chocolate),0.045993,0.203765,0.010285,0.223629,1.097484,0.000914,1.025586,0.093108
4,(avocado),(french fries),0.045993,0.192897,0.011644,0.253165,1.312432,0.002772,1.080697,0.249532
...,...,...,...,...,...,...,...,...,...,...
947,"(spaghetti, tomatoes)",(mineral water),0.030080,0.299825,0.013584,0.451613,1.506253,0.004566,1.276789,0.346524
948,"(mineral water, tomatoes)",(spaghetti),0.034737,0.230157,0.013584,0.391061,1.699106,0.005589,1.264237,0.426262
949,(spaghetti),"(mineral water, tomatoes)",0.230157,0.034737,0.013584,0.059022,1.699106,0.005589,1.025808,0.534466
950,(mineral water),"(spaghetti, tomatoes)",0.299825,0.030080,0.013584,0.045307,1.506253,0.004566,1.015951,0.480025
951,(tomatoes),"(spaghetti, mineral water)",0.092373,0.085193,0.013584,0.147059,1.726183,0.005715,1.072532,0.463502

In [66]:
rules_sorted = rules.sort_values(by='lift', ascending=False)
rules_sorted

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
519,(olive oil),(whole wheat pasta),0.087910,0.040753,0.011062,0.125828,3.087575,0.007479,1.097320,0.741288
518,(whole wheat pasta),(olive oil),0.040753,0.087910,0.011062,0.271429,3.087575,0.007479,1.251888,0.704846
906,"(mineral water, milk)",(soup),0.067922,0.071221,0.012420,0.182857,2.567474,0.007583,1.136618,0.655001
907,(soup),"(mineral water, milk)",0.071221,0.067922,0.012420,0.174387,2.567474,0.007583,1.128953,0.657327
391,(herb & pepper),(ground beef),0.066757,0.136425,0.022899,0.343023,2.514365,0.013792,1.314468,0.645368
...,...,...,...,...,...,...,...,...,...,...
282,(shrimp),(french fries),0.099166,0.192897,0.014555,0.146771,0.760876,-0.004574,0.945939,-0.258639
748,"(mineral water, eggs)",(french fries),0.070056,0.192897,0.010091,0.144044,0.746741,-0.003422,0.942926,-0.267240
753,(french fries),"(mineral water, eggs)",0.192897,0.070056,0.010091,0.052314,0.746741,-0.003422,0.981278,-0.295879
751,(mineral water),"(eggs, french fries)",0.299825,0.046575,0.010091,0.033657,0.722643,-0.003873,0.986632,-0.354073
750,"(eggs, french fries)",(mineral water),0.046575,0.299825,0.010091,0.216667,0.722643,-0.003873,0.893840,-0.287017

# Interview Questions:

# 1.	What is lift and why is it important in Association rules?

The lift value is an important measure in association rule mining because it provides a way to distinguish between significant and insignificant association rules. 
A high lift value indicates that the association rule is more significant, as it suggests that the two items are highly dependent on each other.

# 2.	What is support and Confidence. How do you calculate them?
SUPPORT:
Support is a number of transactions in which antecedent and consequent appear in the data

calculation:

Transaction with antecedent and consequent / Total Transactions


CONFIDENCE:
Confidence is a number of antecedent transactions that also have the consequent item set

Calculation:

Transactions with antecedent and consequent /TransactionÂ withÂ anteceden

# 3.	What are some limitations or challenges of Association rules mining?
In data mining, association rules are useful for analyzing and predicting customer behavior. The primary disadvantages of association rule algorithms are obtaining boring rules, having a large number of discovered rules, and low algorithm performance.